### ISSUE TITLE
default options use a invalid url

### ISSUE THREAD

**Issue by Fjox** [Georift/install-jellyfin-tizen#44]
```root@Hostnetwork:~# docker run --rm ghcr.io/georift/install-jellyfin-tizen x.x.x.x
Build option not provided, using default one: Jellyfin
You can change it by passing option name as second argument for this script.
Tag URL not provided, using latest available version:
You can change it by passing tag URL as third argument for this script.


        Thanks to https://github.com/jeppevinkel for providing the pre-packaged jellyfin-tizen builds!
        These builds can be found at https://github.com/jeppevinkel/jellyfin-tizen-builds

        Using Jellyfin Tizen Build Jellyfin.wgt
        from release:


Attempting to connect to Samsung TV at IP address x.x.x.x
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to x.x.x.x:26101 ...
connected to x.x.x.x:26101
Attempting to get the TV name...
Found TV name: <redacted>
Attempting to install jellyfin-tizen-builds Jellyfin.wgt from release:
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/download//Jellyfin.wgt
There is no package with named Jellyfin.wgt.
[Fail] Fail install. There is the problem about package.
Total time: 00:00:00.880
```
as you can see its trying to grab a url with // wich is invalid

**Comment by Georift** [comment]
Hmm that's interesting, I just ran the container and didn't encounter this. I wonder if you're still having the issue?

It is a result coming from a network call, so we should probably add a check there to warn that we were unable to get a version string from the network.

**Comment by Georift** [comment]
I've added a few more checks, I'll merge this shortly so hopefully in future we'll know whats causing this issue for us.

**Comment by Georift** [comment]
I've merged this now, I wonder if you could try again with the latest build, `sha-dcc4e93` or `latest`.

**Comment by Fjox** [comment]
> @Fjox I've merged this now, I wonder if you could try again with the latest build, `sha-dcc4e93` or `latest`.

I don't have another Samsung TV to try this onand I really don't want to do anything that  old break my current installation...

**Comment by berkerdemirer** [comment]
I am having the same issue running the following command on windows terminal:

`docker run --rm -v "C:\Users\berker\SamsungCertificate\home:/certificates" ghcr.io/georift/install-jellyfin-tizen 192.168.68.50 Jellyfin Jellyfin-master [password]`

Output:
`Attempting to connect to Samsung TV at IP address 192.168.68.50
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.68.50:26101 ...
connected to 192.168.68.50:26101
Attempting to get the TV name...
Found TV name: QE65LS03DAUXXH
Downloading jellyfin-tizen-builds Jellyfin.wgt from release: Jellyfin-master

Attempting to sign package using provided certificate
Specify location of the working directory.
Attempting to install jellyfin-tizen-builds Jellyfin.wgt from release: Jellyfin-master
There is no package with named Jellyfin.wgt.
[Fail] Fail install. There is the problem about package.
Total time: 00:00:00.197`

**Comment by Lem0nbleach** [comment]
@Georift 
` ✘ lem0nbleach@docker-host  ~  docker run --rm ghcr.io/georift/install-jellyfin-tizen 192.168.88.110                       
Build option not provided, using default one: Jellyfin
You can change it by passing option name as second argument for this script.
Error: Could not fetch the latest tag URL from https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/latest`

Not fixed. The link used is valid but it doesn't work without manually pass the link in.

`lem0nbleach@docker-host  ~  docker run --rm ghcr.io/georift/install-jellyfin-tizen 192.168.88.110 Jellyfin https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/latest 
Certificate information not provided, using default dev certificate.


	Thanks to https://github.com/jeppevinkel for providing the pre-packaged jellyfin-tizen builds!
	These builds can be found at https://github.com/jeppevinkel/jellyfin-tizen-builds

	Using Jellyfin Tizen Build Jellyfin.wgt
	from release: latest


Attempting to connect to Samsung TV at IP address 192.168.88.110
...`
